using DAL.DTO.Classes;
using NHibernate;

namespace DAL.DAO.Classes
{
	/// <summary>
	/// DAO for accessing <see cref="Person" /> objects.
	/// </summary>
	public sealed partial class PersonDAO : DAOBase<Person, int>, IPersonDAO
	{
		// Do not edit this file! It's content will be overwritten on code-generation.
		public PersonDAO(ISession session)
			: base(session)
		{
		}
	}
}
