using DAL.DTO.Classes;
using NHibernate;

namespace DAL.DAO.Classes
{
	/// <summary>
	/// DAO for accessing <see cref="Voyage" /> objects.
	/// </summary>
	public sealed partial class VoyageDAO : DAOBase<Voyage, int>, IVoyageDAO
	{
		// Do not edit this file! It's content will be overwritten on code-generation.
		public VoyageDAO(ISession session)
			: base(session)
		{
		}
	}
}
