//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggedInPersonIDInterceptor.TestService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestService.ITestService")]
    public interface ITestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/SaveOrUpdateVoyage", ReplyAction="http://tempuri.org/ITestService/SaveOrUpdateVoyageResponse")]
        WcfService.Schema.ResponseHeaderType SaveOrUpdateVoyage(WcfService.Schema.VoyageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/SaveOrUpdateVoyage", ReplyAction="http://tempuri.org/ITestService/SaveOrUpdateVoyageResponse")]
        System.Threading.Tasks.Task<WcfService.Schema.ResponseHeaderType> SaveOrUpdateVoyageAsync(WcfService.Schema.VoyageRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestServiceChannel : LoggedInPersonIDInterceptor.TestService.ITestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestServiceClient : System.ServiceModel.ClientBase<LoggedInPersonIDInterceptor.TestService.ITestService>, LoggedInPersonIDInterceptor.TestService.ITestService {
        
        public TestServiceClient() {
        }
        
        public TestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfService.Schema.ResponseHeaderType SaveOrUpdateVoyage(WcfService.Schema.VoyageRequest request) {
            return base.Channel.SaveOrUpdateVoyage(request);
        }
        
        public System.Threading.Tasks.Task<WcfService.Schema.ResponseHeaderType> SaveOrUpdateVoyageAsync(WcfService.Schema.VoyageRequest request) {
            return base.Channel.SaveOrUpdateVoyageAsync(request);
        }
    }
}
