//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace WcfService.Schema
{


	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TestService.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Request", Namespace="http://tempuri.org/TestService.xsd", IsNullable=false)]
    public partial class RequestHeaderType {
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TestService.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Response", Namespace="http://tempuri.org/TestService.xsd", IsNullable=false)]
    public partial class ResponseHeaderType {
        
        private StatusCodeEnumType statusCodeField;
        
        private string statusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusCodeEnumType StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TestService.xsd")]
    public enum StatusCodeEnumType {
        
        /// <remarks/>
        InvalidFormat,
        
        /// <remarks/>
        Timeout,
        
        /// <remarks/>
        ServerError,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        NotFound,
        
        /// <remarks/>
        NotAvailable,
        
        /// <remarks/>
        AccessDenied,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TestService.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Voyage", Namespace="http://tempuri.org/TestService.xsd", IsNullable=false)]
    public partial class VoyageType {
        
        private int voyageIDField;
        
        private bool voyageIDFieldSpecified;
        
        private string shipNameField;
        
        private string fromLocationField;
        
        private string toLocationField;
        
        private System.DateTime eTDField;
        
        private System.DateTime eTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int VoyageID {
            get {
                return this.voyageIDField;
            }
            set {
                this.voyageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VoyageIDSpecified {
            get {
                return this.voyageIDFieldSpecified;
            }
            set {
                this.voyageIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShipName {
            get {
                return this.shipNameField;
            }
            set {
                this.shipNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FromLocation {
            get {
                return this.fromLocationField;
            }
            set {
                this.fromLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ToLocation {
            get {
                return this.toLocationField;
            }
            set {
                this.toLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ETD {
            get {
                return this.eTDField;
            }
            set {
                this.eTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ETA {
            get {
                return this.eTAField;
            }
            set {
                this.eTAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TestService.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/TestService.xsd", IsNullable=false)]
    public partial class VoyageRequest {
        
        private RequestHeaderType headerField;
        
        private VoyageType bodyField;
        
        /// <remarks/>
        public RequestHeaderType Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public VoyageType Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
    }
}
