using DAL.DAO;
using DAL.DAO.Classes;
using DAL.DTO.Classes;
using DAL.SessionManagement;
using NHibernate;
using System;

namespace DAL.Service.Classes
{
	/// <summary>
	/// Service for accessing <see cref="Person" /> objects.
	/// </summary>
	public sealed partial class PersonService : ServiceBase<Person>, IPersonService
	{
		// Do not edit this file! It's content will be overwritten on code-generation.
		private IPersonDAO contextDAO;

		protected override IDAO<Person, int> ContextDAO
		{
			get { return contextDAO; }
		}

		public PersonService()
			: this(SessionManager.Instance.DefaultSessionKey)
		{
		}

		public PersonService(Guid sessionKey)
			: base(sessionKey)
		{
			ISession session = SessionManager.Instance.GetSession(sessionKey);
			contextDAO = new DAOFactory().GetPersonDAO(session);
		}
	}
}
